image: gradle:7.1.0-jdk11
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  only:
    - master
  script: gradle --console=plain publish
